version: '3'

networks:
  site:
    driver: "bridge"

services:

  nginx:
    image: nginx:stable-alpine
    container_name: site_nginx
    restart: unless-stopped
    ports:
      - "433:433"
      - "8082:80"
    volumes:
      - ./src:/var/www/html/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - site

  mysql:
    image: mysql:8.0
    container_name: site_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/val/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: 'site'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'N3w_p@ssw0rD.' # TODO: Change this
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - site

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site_php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/src
    ports:
      - "9000:9000"
    networks:
      - site

  redis:
    image: redis:6.2.6-alpine
    container_name: site_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      site:

  composer:
    image: composer:latest
    container_name: site_composer
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/src
    working_dir: /var/www/html/src
    depends_on:
      - php
    networks:
      - site

  npm:
    image: node:16.14.2-alpine
    container_name: site_npm
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/src
    working_dir: /var/www/html/src
    entrypoint: [ 'npm' ]
    networks:
      - site

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site_artisan
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/src
    depends_on:
      - mysql
    working_dir: /var/www/html/src
    entrypoint: [ 'php','/var/www/html/src/artisan' ]
    networks:
      - site